// LOCALHOST USERS COLLECTION

### Get all users
GET http://localhost:3000/users 

### Create user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

  {
    "username": "BobbySue",
    "firstName": "Bobby",
    "lastName": "Susan",
    "streetAddress": "230 Bruce Hill Rd",
    "email": "BobSue@example.com",
    "phoneNum": "207-555-5555"
  }


// LOCALHOST MOVIES COLLECTION

### Get all movies
GET http://localhost:3000/movies 

### Get one movie by Id
GET http://localhost:3000/movies/6374ff5e191e03ef27dec2f7

### Get one movie by title
GET http://localhost:3000/movies/title/Hocus%20Pocus

### Get movies by rating
GET http://localhost:3000/movies/rating/PG-13

### Get movies by genre
GET http://localhost:3000/movies/genre/comedy

### Create movie
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

  {
    "title": "Hook",
    "rating": "PG",
    "description": "Peter Pan grows up",
    "genre": "comedy",
    "ownerId": "6374fe62191e03ef27dec2f5",
    "availability": "true",
    "location": "226 Bruce Hill Rd"
  }

### Update movie
PUT http://localhost:3000/movies/6374fedf191e03ef27dec2f6 HTTP/1.1
content-type: application/json

{
    "title": "Hocus Pocus",
    "rating": "PG",
    "description": "Three witches try to cast a spell to reclaim their youth.",
    "genre": "comedy",
    "ownerId": "6374fe62191e03ef27dec2f5",
    "availability": "false",
    "location": "300 Bruce Hill Rd"
}

### Delete movie
DELETE http://localhost:3000/movies/6376b165b284a23c53300ac5 HTTP/1.1