// LOCALHOST USERS COLLECTION

### Get all users
GET http://localhost:3000/users 

### Get one user by Id
GET http://localhost:3000/users/6374fe62191e03ef27dec2f5

### Create user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

  {
    "username": "Timmy",
    "firstName": "Tim",
    "lastName": "Smith",
    "streetAddress": "218 Bruce Hill Rd",
    "email": "timsmith@example.com",
    "phoneNum": "207-555-8888"
  }

### Update user
PUT http://localhost:3000/users/6374fe62191e03ef27dec2f5 HTTP/1.1
content-type: application/json

  {
    "username": "Timmy",
    "firstName": "Tim",
    "lastName": "Smith",
    "streetAddress": "218 Bruce Hill Rd",
    "email": "timsmith@example.com",
    "phoneNum": "207-555-1111"
  }


### Delete user
DELETE http://localhost:3000/users/6375951bd861f472c2103262 HTTP/1.1

// LOCALHOST MOVIES COLLECTION

### Get all movies
GET http://localhost:3000/movies 

### Get one movie by Id
GET http://localhost:3000/movies/6374ff5e191e03ef27dec2f7

### Get one movie by title
GET http://localhost:3000/movies/title/Hocus%20Pocus

### Get movies by rating
GET http://localhost:3000/movies/rating/PG-13

### Get movies by genre
GET http://localhost:3000/movies/genre/comedy

### Create movie
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

  {
    "title": "Hook",
    "rating": "PG",
    "description": "Peter Pan grows up",
    "genre": "comedy",
    "ownerId": "6374fe62191e03ef27dec2f5",
    "availability": "false",
    "location": "300 Bruce Hill Rd"
  }

### Update movie
PUT http://localhost:3000/movies/6374fedf191e03ef27dec2f6 HTTP/1.1
content-type: application/json

{
    "title": "Hocus Pocus",
    "rating": "PG",
    "description": "Three witches try to cast a spell to reclaim their youth.",
    "genre": "comedy",
    "ownerId": "6374fe62191e03ef27dec2f5",
    "availability": "false",
    "location": "300 Bruce Hill Rd"
}

### Delete movie
DELETE http://localhost:3000/movies/6376b306dc535f7efffbd6fd HTTP/1.1


// LOCALHOST BOOKS COLLECTION

### Get all books
GET http://localhost:3000/books 

### Get one book by Id
GET http://localhost:3000/books/6376b660b06610cce064cc31

### Get one book by title
GET http://localhost:3000/books/title/Persuasion

### Get books by author
GET http://localhost:3000/books/author/Jane%20Austen

### Get books by genre
GET http://localhost:3000/books/genre/romance

### Create book
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

  {
    "title": "Mansfield Park",
    "author": "Jane Austen",
    "description": "Sadness and then happiness",
    "genre": "romance",
    "ownerId": "6374fe62191e03ef27dec2f5",
    "availability": "false",
    "location": "300 Bruce Hill Rd"
  }

### Update book
PUT http://localhost:3000/books/6376b734b06610cce064cc3c HTTP/1.1
content-type: application/json

{
    "title": "Persuasion",
    "author": "Jane Austen",
    "description": "Sadness and then happiness",
    "genre": "romance",
    "ownerId": "6374fe62191e03ef27dec2f5",
    "availability": "false",
    "location": "300 Bruce Hill Rd"
}

### Delete book
DELETE http://localhost:3000/books/6376b8313dc2c3df9667833c HTTP/1.1

// LOCALHOST REVIEWS COLLECTION

### Get all reviews
GET http://localhost:3000/reviews 

### Get one review by Id
GET http://localhost:3000/reviews/6376cc411740f4925526da8f

### Get one review by username
GET http://localhost:3000/reviews/username/JWengler

### Get reviews by movie/book id
GET http://localhost:3000/reviews/media/6376b734b06610cce064cc3c

### Create review
POST http://localhost:3000/reviews HTTP/1.1
content-type: application/json

  {
    "username": "Bob",
    "mediaId": "6376b734b06610cce064cc3c",
    "reviewTitle": "Um ...",
    "reviewBody": "I don't understand. Too many people."
  }

### Update review
PUT http://localhost:3000/reviews/6376cd121740f4925526da9c HTTP/1.1
content-type: application/json

  {
    "username": "Bob",
    "mediaId": "6376b734b06610cce064cc3c",
    "reviewTitle": "Um ...",
    "reviewBody": "I don't understand. Too many people. Umm.."
  }

### Delete review
DELETE http://localhost:3000/reviews/6376cd121740f4925526da9c HTTP/1.1